version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python /backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
      -  videos:/projekt/VideoService_Emplocity/videos
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100

    stdin_open: true
    tty: true
volumes:
  videos:
    external: true