version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - videos:/vol/web/media
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=pass
    depends_on:
      - db

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    volumes:
#      - ./frontend:/frontend
#    ports:
#      - 3000:3000
#    environment:
#      - CHOKIDAR_USEPOLLING=true
#      - CHOKIDAR_INTERVAL=100
#    stdin_open: true
#    tty: true

  db:
    image: postgres:16.0-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_EXTENSIONS=postgis,postgis_topology

volumes:
  videos:
  postgres_data:
