# Generated by Django 5.0.2 on 2024-03-18 00:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=250, unique_for_date='uploaded_at')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('PB', 'Public'), ('PR', 'Private')], default='PB', max_length=2)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
